---
###############################################################################
# Jira Service Management Data Center Inventory
###############################################################################

all:
  children:
    jsm:
      hosts:
        localhost:
          ansible_connection: local
