---
# ------------------------------------------------------------
# Jira Service Management Installation Dispatcher
# ------------------------------------------------------------

- name: Display JSM installation method
  ansible.builtin.debug:
    msg:
      - "========================================"
      - "JSM Installation"
      - "Version : {{ jsm_version }}"
      - "Method  : {{ jsm_install_method }}"
      - "========================================"

- name: Validate JSM installation method
  ansible.builtin.assert:
    that:
      - jsm_install_method in ['archive', 'installer']
    fail_msg: >
      Invalid jsm_install_method={{ jsm_install_method }}.
      Supported methods are archive and installer.

# ------------------------------------------------------------
# Archive Installation
# ------------------------------------------------------------

- name: Install JSM using archive
  ansible.builtin.include_tasks: install_archive.yml
  when: jsm_install_method == "archive"

# ------------------------------------------------------------
# Linux Binary Installer
# ------------------------------------------------------------

- name: Install JSM using Linux binary installer
  ansible.builtin.include_tasks: install_installer.yml
  when: jsm_install_method == "installer"
