---
# ------------------------------------------------------------
# Jira Service Management Data Center
# ------------------------------------------------------------

# ------------------------------------------------------------
# Precheck
# ------------------------------------------------------------

- name: Perform JSM pre-installation checks
  ansible.builtin.import_tasks: precheck.yml
  tags:
    - always
    - precheck

# ------------------------------------------------------------
# Prerequisites
# ------------------------------------------------------------

- name: Install JSM prerequisites
  ansible.builtin.import_tasks: prerequisites.yml
  tags:
    - prerequisites

# ------------------------------------------------------------
# Install
# ------------------------------------------------------------

- name: Install Jira Service Management
  ansible.builtin.import_tasks: install.yml
  tags:
    - install

# ------------------------------------------------------------
# Configure
# ------------------------------------------------------------

- name: Configure Jira Service Management
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configure

# ------------------------------------------------------------
# Systemd
# ------------------------------------------------------------

- name: Configure JSM systemd service
  ansible.builtin.import_tasks: systemd.yml
  tags:
    - systemd

# ------------------------------------------------------------
# Validate
# ------------------------------------------------------------

- name: Validate Jira Service Management
  ansible.builtin.import_tasks: validate.yml
  tags:
    - validate
