---
###############################################################################
# Jira Service Management Data Center - Uninstall
###############################################################################

- name: Uninstall Atlassian Jira Service Management Data Center
  hosts: all
  become: true
  gather_facts: true

  vars:
    jsm_remove_install_dir: true
    jsm_remove_home: true
    jsm_remove_shared_home: true
    jsm_remove_user: true
    jsm_remove_group: true

  tasks:
    - name: Run JSM uninstall
      ansible.builtin.import_role:
        name: jsm
        tasks_from: uninstall
